<?php

echo "<h1>Hello!</h1>";

// echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary'])."  ";

// echo $this->tag->linkTo(["login", "Login Here!", 'class' => 'btn btn-success']);
 
// $currentDate = new \App\Helper\Date();
// echo "<br>Today is". $currentDate->currentDate();
// echo "<br>Time is". $currentDate->currentTime();

if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Description</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->user_id; ?></td>
                <td><?php echo $user->username; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->password; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}